server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/JohnnatanTomaz/AEK_Properties.git
          skip-ssl-validation: true
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}